### ISSUE TITLE
Synchronize/lock multiple concurrent calls to same key in memoryCache.wrap

### ISSUE THREAD

**Issue by nitzanav** [BryanDonovan/node-cache-manager#125] opened 2019-04-21 21:20 UTC
Use case:

The regular code from the example:
```js
function getCachedUser(id, cb) {
    memoryCache.wrap(id, function (cacheCallback) {
        getUser(id, cacheCallback); // slowwwwww takes 1 second
    }, {ttl: ttl}, cb);
}
```

But what happens in my use case is that I have 10 requests to `getCachedUser` at the very same moment for the same `id` and it takes 1 second to fetch the user. 

The result is that while the first call to `getUser` is in progress, the other calls to `getCachedUser` will start too, and all together will tap `getUser` method on the same key.

Of course that the issue is that I am planning to have millions of calls getCachedUser and the system behaves in a way that the calls to the same id are done all at once.

My workaround is to lock / synchronize all calls to the same `id`, and give a chance to the first one to finish, and let the others read from cache after they waited. Using https://www.npmjs.com/package/lock

And here are two options:

```js
function getCachedUser(id, cb) {
    memoryCache.get(id, function(err, result) {
            if (err) {
                return cb(err);
            }
            if (result) {
                return cb(null, result);
            }

            // wait for the first one to finish, then go one by one to the critical session
            lock.acquire(id, function(release) {
                    release_and_cb = function(err, result) {
                        release();
                        return cb(null, result);
                    };

                    memoryCache.wrap(id, function(cacheCallback) {
                        getUser(id, cacheCallback);
                    }, {
                        ttl: ttl
                    }, release_and_cb);
                }
            });
    }
}
```

or simply 
```js
function getCachedUser(id, cb) {
    lock.acquire(id, function(release) {
            release_and_cb = function(err, result) {
                release();
                return cb(null, result);
            };
            memoryCache.wrap(id, function(cacheCallback) {
                getUser(id, cacheCallback);
            }, {
                ttl: ttl
            }, release_and_cb);
        }
    }
}
```

Does anyone doing  this?
Do you think this is a good solution? do you think that the second option has performance issue in high scale?
Do you think that this use case should / can be part of this package?

**Comment by nitzanav** [comment] 2019-04-22 23:06
I have seen a tip here https://www.npmjs.com/package/cached#cachegetorelsekey-value-opts-cb---promisevalue that when you cache a promise, it is promised that it will execute once.

So this will work better:
```
memoryCache.wrap(key, function() {
    return getUserPromise(userId);
})
.then(function(user) {
    console.log('User:', user);
});
```

But it is said that we have to take care that once the promise rejects, we need to clear the cache and avoid caching a rejected promise.

I will be happy to get any input.

**Comment by BryanDonovan** [comment] 2019-05-01 19:24
Sorry for the delayed response.  I think this use-case is covered by the `callbackFiller` code here: https://github.com/BryanDonovan/node-cache-manager/blob/master/lib/caching.js#L122

**Comment by shusson** [comment] 2019-06-06 10:28
@nitzanav This is a pretty common use case with cache implementations for example see nginx [proxy_cache_lock](https://nginx.org/en/docs/http/ngx_http_proxy_module.html?&_ga=2.243311493.1203143906.1559816442-2138067929.1558094109#proxy_cache_lock). I would like to see this be part of the package, @BryanDonovan can you explain a bit how `callbackFiller` meets this use case?

**Comment by BryanDonovan** [comment] 2019-06-06 16:33
I haven't tried this particular case myself, but I was thinking the `callbackFiller` would queue up all requests with the same key so they don't all get sent at once.  At least that's the idea of it.

**Comment by alekseytupichenkov** [comment] 2019-08-19 11:18
Hi all, I wrote a small test to check how `cache-manager` works, in this test I wrap slow method and call it 3 times per each `userId`
```js
const cacheManager = require('cache-manager')

const memoryCache = cacheManager.caching({ store: 'memory', max: 100, ttl: 10/* seconds */ })
const delay = 3000

function getUserSlowRequest(userId) {
    console.log(`call getUserSlowRequest ${userId}`)

    return new Promise(res => setTimeout(() => {
        console.log(`return data getUserSlowRequest ${userId}`)

        res({ id: userId, foo: 'bar' })
    }, delay))
}

async function getCachedUser(userId) {
    return memoryCache.wrap(`user_${userId}`, async () => getUserSlowRequest(userId))
}

async function test() {
    console.log('start')
    console.log(await Promise.all([
        getCachedUser(1),
        getCachedUser(2),
        getCachedUser(3),
        getCachedUser(1),
        getCachedUser(2),
        getCachedUser(3),
        getCachedUser(1),
        getCachedUser(2),
        getCachedUser(3),
    ]))
    console.log('end')
}

test().then()
```

After check, I think that `cache-manager` works perfectly because it calls slow method just once per each `userId`

```
start
call getUserSlowRequest 1
call getUserSlowRequest 2
call getUserSlowRequest 3
return data getUserSlowRequest 1
return data getUserSlowRequest 2
return data getUserSlowRequest 3
[ { id: 1, foo: 'bar' },
  { id: 2, foo: 'bar' },
  { id: 3, foo: 'bar' },
  { id: 1, foo: 'bar' },
  { id: 2, foo: 'bar' },
  { id: 3, foo: 'bar' },
  { id: 1, foo: 'bar' },
  { id: 2, foo: 'bar' },
  { id: 3, foo: 'bar' } ]
end
```

**Comment by BryanDonovan** [comment] 2019-08-22 17:21
Thanks for sharing this, @alekseytupichenkov!

**Comment by glen-84** [comment] 2020-12-30 07:35
Duplicate of #88 (?).

**Closed** 2021-03-15 23:04 UTC

**Comment by mkonikov** [comment] 2024-09-16 18:09
This seems to work fine for single cache but fails for muli-cache.

Modifying the example from @alekseytupichenkov to use a multiCache
```javascript
const cacheManager = require('cache-manager');
const { redisStore } = require('cache-manager-ioredis-yet');
const { REDIS_HOST } = process.env;

let proxyLayeredCache;
const setupCache = async () => {
  const memoryCache = await cacheManager.caching('memory', {
    max: 100,
    ttl: 10,
  });

  const store = await redisStore({
    host: REDIS_HOST,
    ttl: 999999999,
  });
  const redisCache = await cacheManager.caching(store);
  proxyLayeredCache = cacheManager.multiCaching([memoryCache, redisCache].filter(Boolean));

};

const delay = 3000;

function getUserSlowRequest(userId) {
  console.log(`call getUserSlowRequest ${userId}`);

  return new Promise(res => setTimeout(() => {
    console.log(`return data getUserSlowRequest ${userId}`);

    res({ id: userId, foo: 'bar' });
  }, delay));
}

async function getCachedUser(userId) {
  return proxyLayeredCache.wrap(`user_${userId}`, async () => getUserSlowRequest(userId));
}

async function test() {
  console.log('start');
  await setupCache();
  console.log(await Promise.all([
    getCachedUser(1),
    getCachedUser(2),
    getCachedUser(3),
    getCachedUser(1),
    getCachedUser(2),
    getCachedUser(3),
    getCachedUser(1),
    getCachedUser(2),
    getCachedUser(3),
  ]));
  console.log('end');
}

test().then();
```

produces this results in logs
```
start
call getUserSlowRequest 1
call getUserSlowRequest 2
call getUserSlowRequest 3
call getUserSlowRequest 1
call getUserSlowRequest 2
call getUserSlowRequest 3
call getUserSlowRequest 1
call getUserSlowRequest 2
call getUserSlowRequest 3
return data getUserSlowRequest 1
return data getUserSlowRequest 2
return data getUserSlowRequest 3
return data getUserSlowRequest 1
return data getUserSlowRequest 2
return data getUserSlowRequest 3
return data getUserSlowRequest 1
return data getUserSlowRequest 2
return data getUserSlowRequest 3
[
  { id: 1, foo: 'bar' },
  { id: 2, foo: 'bar' },
  { id: 3, foo: 'bar' },
  { id: 1, foo: 'bar' },
  { id: 2, foo: 'bar' },
  { id: 3, foo: 'bar' },
  { id: 1, foo: 'bar' },
  { id: 2, foo: 'bar' },
  { id: 3, foo: 'bar' }
]
end
```

Wondering if there's any built in way to handle stampede also when using multi-cache.
